### ISSUE TITLE
Move MeshTab

### ISSUE THREAD

**Issue by aljesusg** [kiali/openshift-servicemesh-plugin#108]
The MeshTab has some views related with the resoruce:

- Istio View
- Service View
- Workload View

Subissues:

- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/115
- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/142
- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/150

So we need to migrate this step by step:

See 

`
 let iFrameUrl = kialiUrl.baseUrl + '/console/namespaces/' + namespace + '/' + type + '/' + id + '?' + kioskUrl() + '&'
        + kialiUrl.token + '&duration=' + userProps.duration + '&timeRange=' + userProps.timeRange;
    if (!type) {
        const configType = configTypes[items[1].substring(items[1].lastIndexOf('~')+1)].toLowerCase();
        iFrameUrl = kialiUrl.baseUrl + '/console/namespaces/' + namespace + '/istio/' + configType + '/' + id + '?' + kioskUrl() + '&'
            + kialiUrl.token + '&duration=' + userProps.duration + '&timeRange=' + userProps.timeRange;
    }
    // Projects is a special case that will forward the graph in the iframe
    if (items[1] === 'projects') {
        iFrameUrl = kialiUrl.baseUrl +  '/console/graph/namespaces?namespaces=' + id + '&' + kioskUrl() + '&' + kialiUrl.token
            + '&duration=' + userProps.duration + '&timeRange=' + userProps.timeRange;
    }
`

**Comment by ferhoyos** [comment]
Closing since parent epic #109 is closed
