### ISSUE TITLE
Move OSSMC Plugin to native

### ISSUE THREAD

**Issue by aljesusg** [kiali/openshift-servicemesh-plugin#109]
# Tasks

**On Backlog**
- [x] https://github.com/kiali/kiali/issues/5906 (closed, won't do)
- [x] https://github.com/kiali/kiali/issues/5916 
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/107
- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/108
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/110
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/113
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/114
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/119
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/143
- [ ] Link handling
- [ ] Patternfly update to be equivalent to OS 4.14 versions
- [ ] Dark Mode

**Under consideration/Future**
- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/60

**Comment by ferhoyos** [comment]
Closing since it is replaced by #157
