### ISSUE TITLE
Make OSSMC Plugin become GA

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#157]
OSSMC plugin is currently in tech preview and it should be promoted to GA. There are multiple requirements to achieve this target:
- The plugin cannot be based on iframes but native React components
- Follow Openshift Dynamic plugin general guidelines (https://docs.openshift.com/container-platform/4.13/web_console/dynamic-plugin/overview-dynamic-plugin.html)

To get rid of iframes and avoid code duplicity, an unmodifiable version of kiali frontend code will be copied from [#kiali/kiali](https://github.com/kiali/kiali). For this reason some modifications need to be addressed to kiali repository to make it compatible with OSSMC plugin.

Issues to be performed in [#kiali/kiali](https://github.com/kiali/kiali) will be tracked here:
- [x] https://github.com/kiali/kiali/issues/6261

Issues to be performed in this repository:
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/158
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/161
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/166
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/159
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/160
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/173
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/180
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/199

Patternfly Graph
- [ ] https://github.com/kiali/openshift-servicemesh-plugin/issues/99

**Comment by ferhoyos** [comment]
Epic completed!

Although epic https://github.com/kiali/openshift-servicemesh-plugin/issues/99 is still opened, the part related to OSSMC to become GA is done. For this reason we can consider it completed to OSSMC GA epic point of view.
