### ISSUE TITLE
Reuse Kiali cypress tests for OSSMC

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#356]
### What do you want to improve?

Reuse Kiali tests for OSSMC

### What is the current behavior?

Currently, we assume that cypress tests executed for Kiali are valid for OSSMC as well, but some recent issues that only affect OSSMC makes this assumption invalid. 

### What is the new behavior?

The new approach mirrors how we handle the Kiali code. All Kiali Cypress tests are copied into the test folder every sprint, and by configuration, we select which tests are applicable to OSSMC.

Some tasks have to be addressed for this epic:

- [X] https://github.com/kiali/openshift-servicemesh-plugin/pull/373
- [X] https://github.com/kiali/openshift-servicemesh-plugin/pull/357
- [X] https://github.com/kiali/kiali/pull/7656
- [X] https://github.com/kiali/openshift-servicemesh-plugin/pull/376
- [x] [Include OSSMC tests in nightly upstream job](https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration/-/merge_requests/515)

**Comment by ferhoyos** [comment]
The epic to reuse the Kiali tests in OSSMC is completed :tada:
