### ISSUE TITLE
Patternfly topology for Kiali graph

### ISSUE THREAD

**Issue by jshaughn** [kiali/openshift-servicemesh-plugin#99]
One goal of OpenShift plugins is to offer consistent UX (user experience) with both native console and other plugins.  This consistent UX may end up being an acceptance criteria for acceptance as an official plugin for RHOS (and not just a community plugin, or tech preview).  The Kiali graph offer a very different look and feel from other topology views in OS, such as dev console, netobserv, and others.  If feasible it could be a beneficial for Kiali to offer a PF topology option.

**POC / Initial Impl**
- [x] Research PFTopology as a POC [(Summary Here)](https://github.com/kiali/openshift-servicemesh-plugin/issues/100#issuecomment-1362912032)
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/100
- [x] add mechanism to show/hide PFT graph option (done as part of OSSMC-100)

**Things needed for OSSMC GA**
- [x] #202
- [x] https://github.com/kiali/kiali/issues/6370
- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/183
- [x] #203
- [x] this is a placeholder for GA review issues (no issues blocking OSSMC GA)

**Improvements (removing code customizations and contributions to PF)**

- [x] https://github.com/kiali/openshift-servicemesh-plugin/issues/223
- [x] #224
- [x] #225
- [x] https://github.com/patternfly/react-topology/issues/122
- [x] https://github.com/patternfly/react-topology/issues/113

**Additional Issues**
Things that are still a delta between the Cy graph and the PF graph impls.  Some may not be doable or may require a contribution to PFT.  Note that even some of the earlier work may be better supported with a PFT contribution.

**Must Have for Cytoscape deprecation (2.0):**
- [x] support for rectangular boxing (PFT5 see https://github.com/patternfly/react-topology/issues/113)
- [x] solution for node label overlap (PFT5 see https://github.com/patternfly/react-topology/issues/126)
- [x] support for wizard context menu items (PFT5, see https://github.com/patternfly/react-topology/issues/15)
- [x] support for scaled-label-on-hover (I think this may be coming in PFT 5.4) 
- [x] support for group label-on-hover (I think this may be coming in PFT 5.4)
- [x] [support for node "focus"](https://github.com/kiali/kiali/issues/7444)
- [x] at least one acceptable layout option
- [x] https://github.com/kiali/kiali/pull/7799
- [x] https://github.com/kiali/kiali/issues/7785
- [x] https://github.com/kiali/kiali/issues/7770
- [x] https://github.com/kiali/kiali/issues/7780
- [x] https://github.com/kiali/kiali/issues/7781
- [x] https://github.com/kiali/kiali/issues/7803
- [x] https://github.com/kiali/kiali/issues/7807
- [x] https://github.com/kiali/kiali/pull/7831

**Want:**
- [x] https://github.com/kiali/kiali/pull/7816
- [ ] https://github.com/patternfly/react-topology/issues/222

**Nice to Have:**
- [ ] better animation styling
- [ ] support "box-specific" layout options (i.e. always use Dagre for namespace boxes)
- [ ] support vertical ControlBar (in-graph menu)
- [ ] https://github.com/patternfly/react-topology/issues/131 (more layouts supporting groups)

**Optional PFT-specific features we may want to add**
- [ ] Collapsible boxes (groups)
